# Example configuration for gh-commit-ai
# Copy this file to .gh-commit-ai.yml in your repo root or ~/.gh-commit-ai.yml for global config
#
# Configuration priority (highest to lowest):
# 1. Environment variables (e.g., AI_PROVIDER=anthropic gh commit-ai)
# 2. Local config (.gh-commit-ai.yml in repo root)
# 3. Global config (~/.gh-commit-ai.yml in home directory)
# 4. Built-in defaults

# AI Provider Selection
# Options: auto, ollama, anthropic, openai
# Default: auto (automatically detects what's available)
# - "auto" will prefer Ollama (free, local) if running, otherwise tries API providers
# - Ollama: Free, runs locally, requires ollama to be installed and running
# - Anthropic/OpenAI: Requires API key, paid but high quality
ai_provider: auto

# Ollama Configuration
# Model to use when ai_provider is ollama
# Default: gemma3:12b
ollama_model: gemma3:12b

# Ollama API host
# Default: http://localhost:11434
ollama_host: http://localhost:11434

# Anthropic Configuration
# Model to use when ai_provider is anthropic
# Default: claude-3-5-sonnet-20241022
# Options: claude-3-5-sonnet-20241022, claude-3-opus-20240229, etc.
anthropic_model: claude-3-5-sonnet-20241022

# OpenAI Configuration
# Model to use when ai_provider is openai
# Default: gpt-4o-mini
# Options: gpt-4o-mini, gpt-4o, gpt-4-turbo, etc.
openai_model: gpt-4o-mini

# Commit Format Configuration
# Enable/disable conventional commit scopes
# Default: false
# Examples:
#   false: feat: add user authentication
#   true:  feat(auth): add user authentication
use_scope: false

# Enable/disable gitmoji prefixes
# Default: false
# Examples:
#   false: feat: add user authentication
#   true:  ✨ feat: add user authentication
# Gitmoji mappings:
#   ✨ feat (new feature)
#   🐛 fix (bug fix)
#   📝 docs (documentation)
#   💄 style (formatting)
#   ♻️ refactor (code refactoring)
#   ✅ test (adding tests)
#   🔧 chore (tooling/config)
#   🚀 perf (performance)
#   🔒 security (security fix)
use_gitmoji: false

# Performance Configuration
# Maximum number of diff lines to send to AI
# Default: 200
# Lower values = faster, less context
# Higher values = slower, more context
diff_max_lines: 200

# History Learning
# Learn from repository's commit history to match style
# Default: true
# Analyzes last 50 commits for patterns:
# - Scope usage frequency
# - Most common types
# - Capitalization preferences
# - Emoji usage
learn_from_history: true

# Model Recommendations
# Auto-select recommended model based on commit size
# Default: false
# When enabled, automatically selects:
# - Small commits (<100 lines): Faster, cheaper models
# - Medium commits (100-500): Balanced models
# - Large commits (>500 lines): More capable models
# When disabled, shows recommendations as tips
auto_select_model: false

# Note: API keys (ANTHROPIC_API_KEY, OPENAI_API_KEY) cannot be stored in config files
# Set them as environment variables instead:
#   export ANTHROPIC_API_KEY="sk-ant-..."
#   export OPENAI_API_KEY="sk-proj-..."
